In [1]:
import networkx as nx
import numpy as np
import math

g = nx.DiGraph(Directed=True)
g.add_edges_from([('Google','Yahoo'),('Google','Altavista'),('Google','Rediff'),('Google','Bing'),('Google','Wikipedia'), ('Yahoo','Altavista'),('Yahoo','Bing'), ('Altavista','Bing'),('Altavista','Google'), ('Wikipedia', 'Bing'), ('Wikipedia','Google'),('Bing','Google'),('Rediff','Bing')])
e=0.04

L=nx.to_numpy_matrix(g)
Lt=np.transpose(L)
a=[1, 1, 1, 1, 1, 1]
h=[1, 1, 1, 1, 1, 1]
a=np.matrix(a)
h=np.matrix(h)
ax=Lt*L
hx=L*Lt
it=0
while(True):
    it+=1
    print("\n\nIteration: ", it)
    a=np.transpose(a)
    h=np.transpose(h)
    a1=np.dot(ax, a)
    h1=np.dot(hx, h)
    a2=np.array(a1)
    h2=np.array(h1)

    sumsq_a=0
    for i in (np.square(a2)).tolist():
        sumsq_a+=i[0]
    sumsq_a=math.sqrt(sumsq_a)
    a1=a1/sumsq_a
    print("\nAuthority\n", a1)

    sumsq_h=0
    for i in (np.square(h2)).tolist():
        sumsq_h+=i[0]
    sumsq_h=math.sqrt(sumsq_h)
    h1=h1/sumsq_h
    print("\nHub\n", h1)


    count=0
    for i in np.subtract(a1, a):
        if abs(i)<e:
            count+=1
    for i in np.subtract(h1, h):
        if abs(i)<e:
            count+=1
    if count==12:
        break
    a=a1.transpose()
    h=h1.transpose()

    



Iteration:  1

Authority
 [[0.29210312]
 [0.29210312]
 [0.40894437]
 [0.29210312]
 [0.70104749]
 [0.29210312]]

Hub
 [[0.56704798]
 [0.39693358]
 [0.45363838]
 [0.28352399]
 [0.17011439]
 [0.45363838]]


Iteration:  2

Authority
 [[0.29398191]
 [0.25629192]
 [0.39951388]
 [0.25629192]
 [0.74626178]
 [0.25629192]]

Hub
 [[0.62403917]
 [0.40379005]
 [0.41847333]
 [0.27898222]
 [0.13949111]
 [0.41847333]]


Iteration:  3

Authority
 [[0.30486837]
 [0.24583037]
 [0.39294146]
 [0.24583037]
 [0.75588   ]
 [0.24583037]]

Hub
 [[0.64834521]
 [0.40769306]
 [0.40108692]
 [0.27557031]
 [0.12551661]
 [0.40108692]]
